title: Sensory Interface
description: >- # this means to ignore newlines until "baseurl:"
  The Sensory Interface project aims to help people with blindness access data such as graphs and other complex numerical data
# baseurl: "" # the subpath of your site, e.g. /blog

# url: 'https://hasadna.github.io'
url: 'https://s0ands0.github.io'


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata


language:
  code: en


# Collection settings
collections_dir: public
collections:
  about:
    output: true
    permalink: /:collection/:name/

  index:
    output: true
    permalink: /:collection/:name/

  tutorial:
    output: true
    permalink: /:collection/:name/

  privacy:
    output: true
    permalink: /:collection/:name/
